<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.27">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Bence Ságvári">

<title>Data Practices 2026: Introduction to Data Manipulation with dplyr</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="Week_3_R_data_manipulation_files/libs/clipboard/clipboard.min.js"></script>
<script src="Week_3_R_data_manipulation_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="Week_3_R_data_manipulation_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="Week_3_R_data_manipulation_files/libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="Week_3_R_data_manipulation_files/libs/quarto-html/popper.min.js"></script>
<script src="Week_3_R_data_manipulation_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="Week_3_R_data_manipulation_files/libs/quarto-html/anchor.min.js"></script>
<link href="Week_3_R_data_manipulation_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="Week_3_R_data_manipulation_files/libs/quarto-html/quarto-syntax-highlighting-ed96de9b727972fe78a7b5d16c58bf87.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="Week_3_R_data_manipulation_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="Week_3_R_data_manipulation_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="Week_3_R_data_manipulation_files/libs/bootstrap/bootstrap-d6a003b94517c951b2d65075d42fb01b.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">


</head>

<body class="fullcontent quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Data Practices 2026: Introduction to Data Manipulation with dplyr</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Bence Ságvári </p>
          </div>
  </div>
    
  
    
  </div>
  


</header>


<section id="introduction-to-data-practices" class="level2">
<h2 class="anchored" data-anchor-id="introduction-to-data-practices">Introduction to Data Practices</h2>
<p>In empirical research, raw data is rarely ready for statistical modeling. We spend a vast majority of our time cleaning, reshaping, and summarizing data. The <code>dplyr</code> package—part of the broader “Tidyverse” ecosystem—provides a grammar for these data manipulation tasks.</p>
<p>In this tutorial, we will focus on reading code like a sentence using “pipes” and manipulating rows of a dataset.</p>
<section id="setup-and-the-sandbox-dataset" class="level3">
<h3 class="anchored" data-anchor-id="setup-and-the-sandbox-dataset">1. Setup and the Sandbox Dataset</h3>
<p>First, we need to load our tools and our data. If you have never used these packages before, you would first need to install them using <code>install.packages(c("dplyr", "babynames"))</code> in your console.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Load the necessary libraries</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr) <span class="co"># be aware that dplyr is part of tidyverse, so if you already loaded tidyverse, you don't need dplyr separately...</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(babynames)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Let's look at the structure of our dataset</span></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(babynames)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 1,924,665
Columns: 5
$ year &lt;dbl&gt; 1880, 1880, 1880, 1880, 1880, 1880, 1880, 1880, 1880, 1880, 1880,…
$ sex  &lt;chr&gt; "F", "F", "F", "F", "F", "F", "F", "F", "F", "F", "F", "F", "F", …
$ name &lt;chr&gt; "Mary", "Anna", "Emma", "Elizabeth", "Minnie", "Margaret", "Ida",…
$ n    &lt;int&gt; 7065, 2604, 2003, 1939, 1746, 1578, 1472, 1414, 1320, 1288, 1258,…
$ prop &lt;dbl&gt; 0.07238359, 0.02667896, 0.02052149, 0.01986579, 0.01788843, 0.016…</code></pre>
</div>
</div>
<p><strong>Line-by-Line Explanation:</strong></p>
<ul>
<li><code>library(...)</code>: This command loads a package into your current R session, making its functions available to you.</li>
<li><code>glimpse(...)</code>: A <code>dplyr</code> function that transposes the data, allowing you to see every column name, its data type (e.g., <code>&lt;int&gt;</code> for integer, <code>&lt;chr&gt;</code> for character), and the first few rows of data.</li>
</ul>
</section>
<section id="the-pipe-writing-code-like-a-sentence" class="level3">
<h3 class="anchored" data-anchor-id="the-pipe-writing-code-like-a-sentence">2. The Pipe: Writing Code Like a Sentence</h3>
<p>Historically, R code was written from the inside out, nesting functions within functions (e.g., <code>leave_house(get_dressed(wake_up(me)))</code>). This is mathematically sound but cognitively difficult to read.</p>
<p>In modern R (and standard practice in 2026), we use the native pipe operator <code>|&gt;</code>. The pipe takes the object on its left and passes it as the <em>first argument</em> to the function on its right. It translates to the phrase <strong>“and then”</strong>.</p>
<p>In some R code you might see <code>%&gt;%</code> instead of <code>|&gt;</code>. They are (more or less) the same, but <code>%\&gt;%</code> was part of the magittr package (part of tidyverse).</p>
<p><em>Modern R formulation:</em> <code>me |&gt; wake_up() |&gt; get_dressed() |&gt; leave_house()</code></p>
<p>Let’s see this in action with actual data.</p>
</section>
<section id="row-manipulation-filtering" class="level3">
<h3 class="anchored" data-anchor-id="row-manipulation-filtering">3. Row Manipulation: Filtering</h3>
<p>The <code>filter()</code> function allows you to subset rows based on logical conditions (finding rows where a statement is <code>TRUE</code>).</p>
<p><strong>The Goal:</strong> Extract all records for the name “Marie” in the year 1920.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>marie_1920 <span class="ot">&lt;-</span> babynames <span class="sc">|&gt;</span> </span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(name <span class="sc">==</span> <span class="st">"Marie"</span>, year <span class="sc">==</span> <span class="dv">1920</span>)</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(marie_1920)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 5
   year sex   name      n      prop
  &lt;dbl&gt; &lt;chr&gt; &lt;chr&gt; &lt;int&gt;     &lt;dbl&gt;
1  1920 F     Marie 12743 0.0102   
2  1920 M     Marie    31 0.0000282</code></pre>
</div>
</div>
<p><strong>Line-by-Line Explanation:</strong></p>
<ul>
<li><p><code>marie_1920 &lt;-</code>: The assignment arrow <code>&lt;-</code> stores the result of our code into a new object named <code>marie_1920</code> in your computer’s memory.</p></li>
<li><p><code>babynames |&gt;</code>: Take the <code>babynames</code> dataset <strong>and then</strong>…</p></li>
<li><p><code>filter(name == "Marie", year == 1920)</code>: Keep only the rows where the column <code>name</code> is exactly equal to “Marie” AND the column <code>year</code> is exactly equal to 1920.</p></li>
<li><p><em>Note on Syntax:</em> We use a double equals sign <code>==</code> for logical testing (asking “is it equal?”). A single equals sign <code>=</code> is used for assigning values. The comma <code>,</code> acts as an “AND” operator.</p></li>
<li><p><code>head(...)</code>: Prints the first 6 rows of our new object.</p></li>
</ul>
</section>
<section id="row-manipulation-arranging-sorting" class="level3">
<h3 class="anchored" data-anchor-id="row-manipulation-arranging-sorting">4. Row Manipulation: Arranging (Sorting)</h3>
<p>The <code>arrange()</code> function orders the rows of a data frame by the values of selected columns.</p>
<p><strong>The Goal:</strong> Find the years where the name “Marie” was most popular by sorting the data.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>marie_sorted <span class="ot">&lt;-</span> babynames <span class="sc">|&gt;</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(name <span class="sc">==</span> <span class="st">"Marie"</span>, sex <span class="sc">==</span> <span class="st">"F"</span>) <span class="sc">|&gt;</span></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(n))</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(marie_sorted)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 5
   year sex   name      n    prop
  &lt;dbl&gt; &lt;chr&gt; &lt;chr&gt; &lt;int&gt;   &lt;dbl&gt;
1  1920 F     Marie 12743 0.0102 
2  1918 F     Marie 12589 0.0105 
3  1921 F     Marie 12502 0.00977
4  1919 F     Marie 12009 0.0102 
5  1922 F     Marie 11912 0.00955
6  1917 F     Marie 11812 0.0105 </code></pre>
</div>
</div>
<p><strong>Line-by-Line Explanation:</strong></p>
<ul>
<li><code>filter(...)</code>: We first isolate female babies named Marie.</li>
<li><code>arrange(desc(n))</code>: We order the rows by the column <code>n</code> (the count of babies). We wrap <code>n</code> in <code>desc()</code> to sort in <strong>descending</strong> order (highest to lowest). Without <code>desc()</code>, it would default to ascending order.</li>
</ul>
</section>
<section id="row-manipulation-slicing" class="level3">
<h3 class="anchored" data-anchor-id="row-manipulation-slicing">5. Row Manipulation: Slicing</h3>
<p>Sometimes you don’t want to filter by a condition, but rather select rows based on their physical position or statistical rank using <code>slice()</code>.</p>
<p>The <code>slice_</code> family of functions allows us to extract rows based on their rank, their physical position in the dataset, or through random sampling. Let’s explore the four other primary slicing functions using the <code>babynames</code> sandbox. #### A. slice_max(): Finding the Top Values <strong>The Goal:</strong> Isolate the absolute top 3 most popular names for male babies in the year 2000.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>top_3_boys_2000 <span class="ot">&lt;-</span> babynames <span class="sc">|&gt;</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(year <span class="sc">==</span> <span class="dv">2000</span>, sex <span class="sc">==</span> <span class="st">"M"</span>) <span class="sc">|&gt;</span></span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">slice_max</span>(<span class="at">order_by =</span> n, <span class="at">n =</span> <span class="dv">3</span>)</span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a>top_3_boys_2000</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 5
   year sex   name        n   prop
  &lt;dbl&gt; &lt;chr&gt; &lt;chr&gt;   &lt;int&gt;  &lt;dbl&gt;
1  2000 M     Jacob   34471 0.0165
2  2000 M     Michael 32035 0.0153
3  2000 M     Matthew 28572 0.0137</code></pre>
</div>
</div>
<p><strong>Line-by-Line Explanation:</strong></p>
<ul>
<li><code>slice_max(...)</code>: This is a highly efficient function that combines sorting and slicing.</li>
<li><code>order_by = n</code>: Tells the function to evaluate the “maximum” based on the count column <code>n</code>.</li>
<li><code>n = 3</code>: Tells the function to keep exactly 3 rows.</li>
</ul>
<section id="b.-slice_min-finding-the-bottom-values" class="level4">
<h4 class="anchored" data-anchor-id="b.-slice_min-finding-the-bottom-values">B. slice_min(): Finding the Bottom Values</h4>
<p><strong>The Goal:</strong> Find the least popular names for female babies in 1990.</p>
<p><em>Methodological Note:</em> The Social Security Administration (who provides this data) excludes names with fewer than 5 occurrences to protect privacy. Therefore, thousands of names are “tied” at exactly 5. We will use a special argument to handle these ties.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>bottom_3_girls_1990 <span class="ot">&lt;-</span> babynames <span class="sc">|&gt;</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(year <span class="sc">==</span> <span class="dv">1990</span>, sex <span class="sc">==</span> <span class="st">"F"</span>) <span class="sc">|&gt;</span></span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">slice_min</span>(<span class="at">order_by =</span> n, <span class="at">n =</span> <span class="dv">3</span>, <span class="at">with_ties =</span> <span class="cn">FALSE</span>)</span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>bottom_3_girls_1990</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 5
   year sex   name        n       prop
  &lt;dbl&gt; &lt;chr&gt; &lt;chr&gt;   &lt;int&gt;      &lt;dbl&gt;
1  1990 F     Aarica      5 0.00000243
2  1990 F     Aasha       5 0.00000243
3  1990 F     Abagale     5 0.00000243</code></pre>
</div>
</div>
<p><strong>Line-by-Line Explanation:</strong></p>
<ul>
<li>slice_min(…): Isolates the rows with the lowest values in our target column.</li>
<li>order_by = n: We evaluate the “minimum” based on the count column n.</li>
<li>n = 3: We want to keep exactly 3 rows.</li>
<li>with_ties = FALSE: Because thousands of names have an n of 5, slice_min() would normally return all of them. Setting this to FALSE forces the function to return exactly 3 rows, breaking ties based on their original order in the dataset.</li>
</ul>
</section>
<section id="c.-slice_head-and-slice_tail-positional-slicing" class="level4">
<h4 class="anchored" data-anchor-id="c.-slice_head-and-slice_tail-positional-slicing">C. slice_head() and slice_tail(): Positional Slicing</h4>
<p>Sometimes you need to inspect the absolute beginning or absolute end of a dataset or subset, regardless of the values inside.</p>
<p><strong>The Goal:</strong> Extract the very first 4 and the very last 4 records for the year 1950 to inspect the data boundaries.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Inspecting the top of the 1950 subset</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>head_1950 <span class="ot">&lt;-</span> babynames <span class="sc">|&gt;</span></span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(year <span class="sc">==</span> <span class="dv">1950</span>) <span class="sc">|&gt;</span></span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">slice_head</span>(<span class="at">n =</span> <span class="dv">4</span>)</span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Inspecting the bottom of the 1950 subset</span></span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a>tail_1950 <span class="ot">&lt;-</span> babynames <span class="sc">|&gt;</span></span>
<span id="cb11-8"><a href="#cb11-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(year <span class="sc">==</span> <span class="dv">1950</span>) <span class="sc">|&gt;</span></span>
<span id="cb11-9"><a href="#cb11-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">slice_tail</span>(<span class="at">n =</span> <span class="dv">4</span>)</span>
<span id="cb11-10"><a href="#cb11-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-11"><a href="#cb11-11" aria-hidden="true" tabindex="-1"></a>head_1950</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 5
   year sex   name         n   prop
  &lt;dbl&gt; &lt;chr&gt; &lt;chr&gt;    &lt;int&gt;  &lt;dbl&gt;
1  1950 F     Linda    80432 0.0457
2  1950 F     Mary     65482 0.0372
3  1950 F     Patricia 47945 0.0273
4  1950 F     Barbara  41557 0.0236</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>tail_1950</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 5
   year sex   name        n       prop
  &lt;dbl&gt; &lt;chr&gt; &lt;chr&gt;   &lt;int&gt;      &lt;dbl&gt;
1  1950 M     Zackary     5 0.00000275
2  1950 M     Zannie      5 0.00000275
3  1950 M     Zeke        5 0.00000275
4  1950 M     Zygmunt     5 0.00000275</code></pre>
</div>
</div>
<p><strong>Line-by-Line Explanation:</strong></p>
<ul>
<li>slice_head(n = 4): Simply extracts rows 1 through 4 of the filtered dataset.</li>
<li>slice_tail(n = 4): Extracts the final 4 rows of the filtered dataset.</li>
</ul>
</section>
<section id="d.-slice_sample-random-subsetting" class="level4">
<h4 class="anchored" data-anchor-id="d.-slice_sample-random-subsetting">D. slice_sample(): Random Subsetting</h4>
<p>In advanced data practices, you will frequently need to take random subsets of your data—perhaps to build a smaller training dataset for a machine learning model, or to run a quick pilot analysis when your main dataset is millions of rows long.</p>
<p><strong>The Goal:</strong> Randomly select 5 baby names from the year 2020.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Set a random seed for reproducible research</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">2026</span>)</span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>random_2020_names <span class="ot">&lt;-</span> babynames <span class="sc">|&gt;</span></span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(year <span class="sc">==</span> <span class="dv">2020</span>) <span class="sc">|&gt;</span></span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">slice_sample</span>(<span class="at">n =</span> <span class="dv">5</span>)</span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-8"><a href="#cb15-8" aria-hidden="true" tabindex="-1"></a>random_2020_names</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 0 × 5
# ℹ 5 variables: year &lt;dbl&gt;, sex &lt;chr&gt;, name &lt;chr&gt;, n &lt;int&gt;, prop &lt;dbl&gt;</code></pre>
</div>
</div>
<p><strong>Line-by-Line Explanation:</strong></p>
<ul>
<li>set.seed(2026): This is a crucial Base R function for reproducible research. Computers generate pseudo-random numbers. By setting a “seed” (in this case, the number 2026), we force the computer to start its random generation process from the exact same mathematical starting point every time. If you run this chunk 100 times, you will get the exact same 5 “random” names.</li>
<li>slice_sample(n = 5): Randomly pulls 5 rows from the dataset.</li>
</ul>
<p><strong>Alternative</strong>: You can also use proportions instead of explicit counts. For example, slice_sample(prop = 0.10) would randomly sample exactly 10% of your data.</p>
</section>
</section>
<section id="methodological-trade-offs-dplyr-vs.-data.table-vs.-base-r" class="level3">
<h3 class="anchored" data-anchor-id="methodological-trade-offs-dplyr-vs.-data.table-vs.-base-r"><code>Methodological Trade-offs: dplyr vs. data.table vs. Base R</code></h3>
<p><code>It is important to understand why we choose specific tools:</code></p>
<ol type="1">
<li><strong><code>Readability (dplyr):</code></strong><code>The pipe syntax makes dplyr highly readable and excellent for reproducible research. The trade-off is that it can be slightly slower on massive datasets (e.g., 50+ million rows) compared to lower-level packages.</code></li>
<li><strong><code>Speed (data.table):</code></strong><code>For massive datasets, data.table is significantly faster and more memory-efficient. However, its syntax is terse and has a steeper learning curve for beginners.</code></li>
<li><strong><code>Dependencies (Base R):</code></strong><code>Base R requires no external packages, meaning your code will almost certainly run 20 years from now without package version conflicts. However, base R syntax for complex manipulations is often difficult to read and debug.</code></li>
</ol>
<p><code>For the vast majority of social science and experimental data, the readability and safety of dplyr is the optimal choice.</code></p>
<p>This is a perfect next step. So far, we have mastered manipulating the <em>observations</em> (the rows) of our dataset. However, in advanced data practices—especially when preparing data for statistical modeling or machine learning—you will spend a significant amount of time doing “feature engineering.” This involves selecting the right variables, cleaning up their names, organizing them logically, and mathematically transforming them into new variables (the columns).</p>
<p>Let’s dive into the four foundational <code>dplyr</code> verbs for column manipulation: <code>select()</code>, <code>rename()</code>, <code>relocate()</code>, and the powerhouse, <code>mutate()</code>.</p>
</section>
<section id="column-manipulation-subsetting-with-select" class="level3">
<h3 class="anchored" data-anchor-id="column-manipulation-subsetting-with-select">6. Column Manipulation: Subsetting with select()</h3>
<p>Often, datasets contain dozens or hundreds of variables, but your specific research question only requires three or four. The <code>select()</code> function allows you to keep or drop specific columns.</p>
<p><strong>Methodological Trade-off:</strong> Dropping unnecessary columns early in your script using <code>select()</code> is a highly recommended practice. It significantly reduces the memory footprint of your dataset, making subsequent operations much faster.</p>
<p><strong>The Goal:</strong> Isolate just the year, name, and count (<code>n</code>) columns. We will drop <code>sex</code> and <code>prop</code>.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Approach 1: Explicitly name the columns you want to keep</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>lean_babynames <span class="ot">&lt;-</span> babynames <span class="sc">|&gt;</span></span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(year, name, n)</span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Approach 2: Explicitly name the columns you want to DROP using a minus sign</span></span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a>lean_babynames_alt <span class="ot">&lt;-</span> babynames <span class="sc">|&gt;</span></span>
<span id="cb17-7"><a href="#cb17-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="sc">-</span>sex, <span class="sc">-</span>prop)</span>
<span id="cb17-8"><a href="#cb17-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-9"><a href="#cb17-9" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(lean_babynames)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 3
   year name          n
  &lt;dbl&gt; &lt;chr&gt;     &lt;int&gt;
1  1880 Mary       7065
2  1880 Anna       2604
3  1880 Emma       2003
4  1880 Elizabeth  1939
5  1880 Minnie     1746
6  1880 Margaret   1578</code></pre>
</div>
</div>
<p><strong>Line-by-Line Explanation:</strong></p>
<ul>
<li><code>select(year, name, n)</code>: Tells R to keep only these three columns, in this exact order.</li>
<li><code>select(-sex, -prop)</code>: The negative sign tells R to keep <em>everything except</em> <code>sex</code> and <code>prop</code>. This is often more efficient if you have 50 columns and only want to drop 2.</li>
</ul>
</section>
<section id="column-manipulation-standardizing-with-rename" class="level3">
<h3 class="anchored" data-anchor-id="column-manipulation-standardizing-with-rename">7. Column Manipulation: Standardizing with rename()</h3>
<p>Clean, descriptive variable names are essential for reproducible research. The default names in a raw dataset are rarely publication-ready.</p>
<p><strong>The Goal:</strong> The column name <code>n</code> is a bit ambiguous. Let’s rename it to <code>total_count</code>, and rename <code>prop</code> to <code>proportion</code> for ultimate clarity.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>renamed_babynames <span class="ot">&lt;-</span> babynames <span class="sc">|&gt;</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rename</span>(</span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">total_count =</span> n, </span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">proportion =</span> prop</span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-7"><a href="#cb19-7" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(renamed_babynames)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 5
   year sex   name      total_count proportion
  &lt;dbl&gt; &lt;chr&gt; &lt;chr&gt;           &lt;int&gt;      &lt;dbl&gt;
1  1880 F     Mary             7065     0.0724
2  1880 F     Anna             2604     0.0267
3  1880 F     Emma             2003     0.0205
4  1880 F     Elizabeth        1939     0.0199
5  1880 F     Minnie           1746     0.0179
6  1880 F     Margaret         1578     0.0162</code></pre>
</div>
</div>
<p><strong>Line-by-Line Explanation:</strong></p>
<ul>
<li><code>rename(...)</code>: The function to change column headers.</li>
<li><code>total_count = n</code>: <strong>Crucial Syntax Note:</strong> In <code>dplyr</code>, the syntax is always <code>new_name = old_name</code>. Beginners often flip this and cause an error. Think of it as assigning the old column’s data into your new name.</li>
</ul>
</section>
<section id="column-manipulation-organizing-with-relocate" class="level3">
<h3 class="anchored" data-anchor-id="column-manipulation-organizing-with-relocate">8. Column Manipulation: Organizing with relocate()</h3>
<p>When you look at your dataset, you usually want the most important identifier columns on the far left. The <code>relocate()</code> function allows you to move columns around without dropping any data.</p>
<p><strong>The Goal:</strong> Move the <code>name</code> column to be the very first column in the dataset, before <code>year</code>.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>reordered_babynames <span class="ot">&lt;-</span> babynames <span class="sc">|&gt;</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">relocate</span>(name, <span class="at">.before =</span> year)</span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(reordered_babynames)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 5
  name       year sex       n   prop
  &lt;chr&gt;     &lt;dbl&gt; &lt;chr&gt; &lt;int&gt;  &lt;dbl&gt;
1 Mary       1880 F      7065 0.0724
2 Anna       1880 F      2604 0.0267
3 Emma       1880 F      2003 0.0205
4 Elizabeth  1880 F      1939 0.0199
5 Minnie     1880 F      1746 0.0179
6 Margaret   1880 F      1578 0.0162</code></pre>
</div>
</div>
<p><strong>Line-by-Line Explanation:</strong></p>
<ul>
<li><code>relocate(name)</code>: Tells R which column we want to move.</li>
<li><code>.before = year</code>: This is a “helper” argument. It specifies exactly where <code>name</code> should be placed. You can also use <code>.after = [column_name]</code>. If you don’t specify <code>.before</code> or <code>.after</code>, <code>relocate()</code> defaults to moving the column to the absolute front (position 1).</li>
</ul>
</section>
<section id="column-manipulation-feature-engineering-with-mutate" class="level3">
<h3 class="anchored" data-anchor-id="column-manipulation-feature-engineering-with-mutate">9. Column Manipulation: Feature Engineering with mutate()</h3>
<p>The <code>mutate()</code> function is arguably the most important verb in data manipulation. It allows you to create brand new columns based on mathematical operations applied to existing columns.</p>
<p><strong>The Goal:</strong> The <code>prop</code> column is a decimal (e.g., 0.07). Let’s create a new column called <code>percentage</code> that multiplies the proportion by 100. Let’s also create a logical (TRUE/FALSE) variable indicating if a name had more than 10,000 babies that year, which could be useful for a future regression model.</p>
<p>Code snippet</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>engineered_babynames <span class="ot">&lt;-</span> babynames <span class="sc">|&gt;</span></span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">percentage =</span> prop <span class="sc">*</span> <span class="dv">100</span>,</span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">is_highly_popular =</span> n <span class="sc">&gt;</span> <span class="dv">10000</span></span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">|&gt;</span></span>
<span id="cb23-6"><a href="#cb23-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">relocate</span>(percentage, is_highly_popular, <span class="at">.after =</span> name) <span class="co"># Moving them so we can see them!</span></span>
<span id="cb23-7"><a href="#cb23-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-8"><a href="#cb23-8" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(engineered_babynames)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 7
   year sex   name      percentage is_highly_popular     n   prop
  &lt;dbl&gt; &lt;chr&gt; &lt;chr&gt;          &lt;dbl&gt; &lt;lgl&gt;             &lt;int&gt;  &lt;dbl&gt;
1  1880 F     Mary            7.24 FALSE              7065 0.0724
2  1880 F     Anna            2.67 FALSE              2604 0.0267
3  1880 F     Emma            2.05 FALSE              2003 0.0205
4  1880 F     Elizabeth       1.99 FALSE              1939 0.0199
5  1880 F     Minnie          1.79 FALSE              1746 0.0179
6  1880 F     Margaret        1.62 FALSE              1578 0.0162</code></pre>
</div>
</div>
<p><strong>Line-by-Line Explanation:</strong></p>
<ul>
<li><code>mutate(...)</code>: The function to create or overwrite columns.</li>
<li><code>percentage = prop * 100</code>: Creates a new column named <code>percentage</code>. It goes row by row, taking the value in <code>prop</code>, multiplying it by 100, and storing the result.</li>
<li><code>is_highly_popular = n &gt; 10000</code>: Creates a boolean (logical) column. R evaluates the statement “is <code>n</code> greater than 10,000?” and returns <code>TRUE</code> or <code>FALSE</code> for every single row.</li>
<li><em>Note:</em> By default, <code>mutate()</code> adds new columns to the absolute right side (the end) of your dataset. We used <code>relocate()</code> right after it so the new columns are visible when we print the <code>head()</code>.</li>
</ul>
</section>
<section id="putting-it-all-together-your-turn" class="level3">
<h3 class="anchored" data-anchor-id="putting-it-all-together-your-turn">Putting It All Together: Your Turn</h3>
<p>You now have a powerful toolkit. You can filter rows, sort data, slice the top results, select specific columns, and engineer new mathematical variables.</p>
<p><strong>Your Challenge:</strong> Try to write a single, contiguous pipeline (using <code>|&gt;</code>) that does the following: 1. Takes the <code>babynames</code> dataset. 2. Filters for only male babies (<code>sex == "M"</code>). 3. Creates a new column using <code>mutate()</code> called <code>decade</code> (Hint: you can use <code>floor(year / 10) * 10</code> to mathematically calculate the decade). 4. Selects <em>only</em> the <code>name</code>, <code>decade</code>, and <code>n</code> columns. 5. Arranges the results by <code>n</code> in descending order.</p>
</section>
<section id="moving-beyond-simple-data-manipulation-split-apply-combine---make-real-analysis" class="level3">
<h3 class="anchored" data-anchor-id="moving-beyond-simple-data-manipulation-split-apply-combine---make-real-analysis">10. Moving beyond simple data manipulation: split, apply &amp; combine - make ‘real’ analysis</h3>
<section id="the-split-apply-combine-paradigm" class="level4">
<h4 class="anchored" data-anchor-id="the-split-apply-combine-paradigm">The Split-Apply-Combine Paradigm</h4>
<p>Before writing the code, it is vital to understand the theory. When we group and summarize data, we are asking the computer to: 1. <strong>Split</strong> the dataset into distinct, invisible groups based on a categorical variable (e.g., splitting by <code>year</code>). 2. <strong>Apply</strong> a mathematical function to each group independently (e.g., calculating the sum or the mean). 3. <strong>Combine</strong> the results back into a brand new, highly condensed summary table.</p>
</section>
</section>
<section id="global-aggregation-with-summarize" class="level3">
<h3 class="anchored" data-anchor-id="global-aggregation-with-summarize">11. Global Aggregation with summarize()</h3>
<p>The <code>summarize()</code> function (or <code>summarise()</code>, depending on your spelling preference) collapses your dataset down to a single row based on the math you ask it to perform.</p>
<p><strong>The Goal:</strong> Calculate the absolute total number of babies recorded in the entire <code>babynames</code> dataset across all years.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="co">#\| label: summarize-global</span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>total_babies_ever <span class="ot">&lt;-</span> babynames <span class="sc">|&gt;</span> </span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>( <span class="at">total_records =</span> <span class="fu">n</span>(), <span class="co"># Counts the number of rows </span></span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a>             <span class="at">total_babies =</span> <span class="fu">sum</span>(n) ) <span class="co"># Sums the values in the 'n' column</span></span>
<span id="cb25-6"><a href="#cb25-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-7"><a href="#cb25-7" aria-hidden="true" tabindex="-1"></a>total_babies_ever</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 2
  total_records total_babies
          &lt;int&gt;        &lt;int&gt;
1       1924665    348120517</code></pre>
</div>
</div>
<p><strong>Line-by-Line Explanation:</strong></p>
<ul>
<li><p>summarize(…): The function that tells R we are condensing the data.</p></li>
<li><p>total_records = n(): We create a new column called total_records. The n() function is a special dplyr tool that simply counts the number of rows.</p></li>
<li><p>total_babies = sum(n): We create a new column called total_babies by taking the mathematical sum of the n column.</p></li>
</ul>
<p>Notice: Our dataset of nearly 2 million rows just became a dataset of exactly 1 row.</p>
</section>
<section id="grouped-aggregation-group_by-summarize" class="level3">
<h3 class="anchored" data-anchor-id="grouped-aggregation-group_by-summarize">13. Grouped Aggregation: group_by() + summarize()</h3>
<p>Summarizing the whole dataset is rarely what we want. We usually want statistics <em>by category</em>. We achieve this by piping our data through <code>group_by()</code> immediately before <code>summarize()</code>.</p>
<p><strong>The Goal:</strong> Calculate the total number of babies born <em>per year</em>.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>babies_per_year <span class="ot">&lt;-</span> babynames <span class="sc">|&gt;</span></span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(year) <span class="sc">|&gt;</span></span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">total_babies =</span> <span class="fu">sum</span>(n))</span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-5"><a href="#cb27-5" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(babies_per_year)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 2
   year total_babies
  &lt;dbl&gt;        &lt;int&gt;
1  1880       201484
2  1881       192696
3  1882       221533
4  1883       216946
5  1884       243462
6  1885       240854</code></pre>
</div>
</div>
<p><strong>Line-by-Line Explanation:</strong></p>
<ul>
<li><p><code>group_by(year)</code>: This changes the internal metadata of the dataset. It doesn’t change how the data looks, but it tells R: “For all future calculations, treat every unique year as its own isolated dataset.”</p></li>
<li><p><code>summarize(...)</code>: Because the data is now grouped by year, <code>summarize()</code> will output one row <em>per year</em>, rather than one row total.</p></li>
</ul>
</section>
<section id="advanced-aggregation-multiple-groups-and-metrics" class="level3">
<h3 class="anchored" data-anchor-id="advanced-aggregation-multiple-groups-and-metrics">14. Advanced Aggregation: Multiple Groups and Metrics</h3>
<p>In your research, you will frequently need to calculate multiple summary statistics across intersecting categories (e.g., Control vs.&nbsp;Treatment across different Demographic groups).</p>
<p>The Goal: For every year and every biological sex, calculate the total number of babies born AND find the longest name used in that specific group.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a>yearly_sex_summary <span class="ot">&lt;-</span> babynames <span class="sc">|&gt;</span></span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(year, sex) <span class="sc">|&gt;</span></span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(</span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">total_babies =</span> <span class="fu">sum</span>(n),</span>
<span id="cb29-5"><a href="#cb29-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">longest_name_length =</span> <span class="fu">max</span>(<span class="fu">nchar</span>(name)), </span>
<span id="cb29-6"><a href="#cb29-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">.groups =</span> <span class="st">"drop"</span></span>
<span id="cb29-7"><a href="#cb29-7" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb29-8"><a href="#cb29-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-9"><a href="#cb29-9" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(yearly_sex_summary)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 4
   year sex   total_babies longest_name_length
  &lt;dbl&gt; &lt;chr&gt;        &lt;int&gt;               &lt;int&gt;
1  1880 F            90993                  10
2  1880 M           110491                  11
3  1881 F            91953                  10
4  1881 M           100743                  11
5  1882 F           107847                  10
6  1882 M           113686                  11</code></pre>
</div>
</div>
<p><strong>Line-by-Line Explanation:</strong></p>
<ul>
<li><p>group_by(year, sex): We are now splitting the data into intersecting groups (e.g., 1880-Female, 1880-Male, 1881-Female…).</p></li>
<li><p>longest_name_length = max(nchar(name)): We calculate the number of characters (nchar) for every name in that group, and then find the maximum (max) value.</p></li>
<li><p>.groups = “drop”: Crucial Methodological Best Practice. When you group by multiple variables, dplyr will peel off the last grouping variable after summarizing, but leave the rest of the dataset grouped. This invisible grouping frequently causes severe mathematical errors later in complex scripts. Explicitly dropping the groups guarantees your output is a clean, standard data frame ready for the next step.</p></li>
</ul>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>